version: '3.2'
services:
  elasticserver:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: eleastic_server
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    ports:
      - 9200:9200
  eleasticclient:
    image: elasticsearch:latest
    ports:
      - 8080:8080
    container_name: elastic_client
    depends_on:
      - elasticserver